### ISSUE TITLE
Structs for iri components

### ISSUE THREAD

**Issue by damooo** [lo48576/iri-string#22]
Hello @lo48576 , feel free to close this issue, if it is out of scope for the crate.

It will be great if, there are string invariants for representing iri components like `SegmentStr`, `PathStr`, `AuthorityStr`, etc.. And normalizations for them. This will help in constructing and using those intermediate components in many uri generation, manipulation tasks. It seems, we can refactor already existing code for validating, normalizing them into well defined abstractions.

We can then even return them for methods `path_str`, `segment_str`, etc. instead of plain strings.

**Comment by lo48576** [comment]
I'll define `RiSchemeStr{,ing}`, `RiPathStr{,ing}`, and `RiQueryStr{,ing}` first, and will release them.

However, I'm not sure what to define for components inside `authority`.
It consists of sub components like `userinfo`, `host`, and `port`, and `host` is one of `IP-literal`, `IPv4address`, or `reg-name`.
(And `userinfo` may be `user ":" password`", and `IP-literal` is one of `IPv6addresss` or `IPvFuture` wrapped by brackets.)
Is defining types for every subcomponent really wished?

**Comment by lo48576** [comment]
To be honest, that is the exact reason why I defined [`AuthorityComponents`](https://docs.rs/iri-string/0.5.4/iri_string/components/struct.AuthorityComponents.html) type.
At the time I wrote them, I don't think it was worth doing. So this is not a dedicated string type but proxy type that has methods to return `&str` and `Option<&str>`, and the returned ones are also not dedicated types.

**Comment by lo48576** [comment]
Another thing to handle: `scheme` is commonly used for RFC 3986 and RFC 3987, so spec type parameter for `RiSchemeStr<S>` will be unnecessary... but should I remove this? Or, providing casts between them is enough?

**Comment by lo48576** [comment]
Yet another thing: acceptable `path`s are decided by presence/absence of `authority` part.
Specifically, paths that start with segments with colon (such as `foo:bar/baz`) cannot be used as relative IRI references, and paths that starts with double slashes (such as `//not-a-host`) cannot be used as IRI without `authority`.
Such restrictions will need IRI builders to fail at runtime (even when dedicated `IriPathStr` type is provided), so I'm not sure whether this is really useful.

If the API should be like `IriBuilder::set_path(&mut self, path: &IriPathStr) -> Result<&mut Self, IriBuildError>`, then `path: &str` would be enough for this purpose.

Splitting a path into segments would be useful, but for this purpose it is enough to provide `PathSegments<S>` iterator, not `RiPathStr<S>`.

**Comment by lo48576** [comment]
It turned out that there are more things to consider than I imagined, so I'll put this enhancement on hold until these questions are resolved.
For now I implemented `RiQueryStr{,ing}` and pushed it to `develop` branch (commit 3dbcaf0c94db9512c4518125e1349242e57e970e).

For the feature to construct an IRI, I'll use issue #23.

**Comment by damooo** [comment]
[uriparse-rs](https://docs.rs/uriparse/latest/uriparse/) crate which is not string backed, also seems provides such interfaces. May be any decissions there helpful?

**Comment by lo48576** [comment]
Hmm... Unfortunately I didn't find discussions about usefulness of dedicated types for components in `uriparse-rs` repo.
It seems to me that it is implemented just because it is possible.

Main goals of this crate (`iri-string`) for now are:

* Using dedicated types, users can give guarantee of some useful property and make some operations infallible.
* Making APIs of dedicated types (with guarantee) highly compatible with plain `&str` and `String`.

The reason I'm hesitating implementing `RiPathStr` and similar verbose types are, because I doubt the types can provide enough guarantees.

One of the examples are `"//not-a-host"` (as described in <https://github.com/lo48576/iri-string/issues/22#issuecomment-1108952921>).
`//not-a-host` is completely valid as `path`, but it cannot be used as a path for IRIs without `authority` component... i.e. the guarantee "the string is a valid path" might be too week and not so useful.

I want types to provide guarantees that is strong enough to make some operations infallible.
And if it is not possible, `&str` will be enough for the operation.
So, I'll continue to think about the guarantees I need for the components.

**Comment by lo48576** [comment]
Things I currently think useful are, string types for [`reg-name`](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2), [`userinfo`](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2), and username and password part inside `userinfo`.
These accept different characters in IRI and URI, they accept percent encoding, and they can be generated from untrusted external data.
Providing correct encoding / decoding for them would be quite useful from the security point of view.

I'm willing to implement them, but I'm still thinking how the API should look like for `authority`.

**Comment by lo48576** [comment]
I'll close this issue for now, with the thoughts and resolutions below:

* [`QueryStr{,ing}`](https://docs.rs/iri-string/0.5.6/iri_string/types/type.UriQueryStr.html) is implemented.
    + `FragmentStr{,ing}` has already been provided, so providing this would be quite reasonable.
* I won't implement dedicated string types for other components for now.
    + However, I made some manipulations easy. I'll describe below.
* [IRI builder](https://docs.rs/iri-string/0.5.6/iri_string/build/struct.Builder.html) is implemented.
    + Syntactic restrictions of IRI is not independent for each component. Especially `scheme`, `authority`, and `path` have strong relations and won't be validated without each other in some situations.
    + To handle this syntax, I decided to run validation just once at the `.build()` time, rather than component-wise. So I don't need dedicated types for compontents for this use case.
* [Percent encoder](https://docs.rs/iri-string/0.5.6/iri_string/percent_encode/struct.PercentEncoded.html) is implemented.
    + Using this, users can percent-encode the plain data as they need.
    + Conversion are component-aware (for example [`from_path_segment`](https://docs.rs/iri-string/0.5.6/iri_string/percent_encode/struct.PercentEncoded.html#method.from_path_segment) method for a path segment), and I think this would be practical enough for most cases.

By the updates described above, now components can be manipulated easily than before, and IRI generation would be easy and safe.

**Comment by lo48576** [comment]
I'm not willing to add dedicated types for many components for now, but it does not mean I decided never to do it.
If you strongly want dedicated string types for some specific components, feel free to open new issues (separate issues for each item if possible).
