### ISSUE TITLE
Ergnomics for template::Expand

### ISSUE THREAD

**Issue by nyarly** [lo48576/iri-string#39]
It's surprising that `template::Expand` isn't just `types::RiString`. It might make sense not to expand directly to a `RiString`, but having a conversion directly from `Expand` to `RiString` would be a nice ergonomic feature.

**Comment by lo48576** [comment]
Thank you for reporting.

I didn't make it directly convertible to `RiString` because the the URI template seems to be able to describe non-absolute IRIs (if I didn't overlooked something in [RFC6570](https://www.rfc-editor.org/rfc/rfc6570.html)).

But yeah, it would be ergonomic to provide direct (try-)conversion methods for `template::Expanded` since it is usually used to generate some kind of IRIs.

**Comment by nyarly** [comment]
You're 100% that RFC 6570 allows for strings that aren't URIs to be produced; a `TryInto` is what would be appropriate.

**Comment by lo48576** [comment]
Released as v0.7.3 ([CHANGELOG](https://github.com/lo48576/iri-string/blob/develop/CHANGELOG.md#073)).
