### ISSUE TITLE
Give template::context::Context a mut receiver

### ISSUE THREAD

**Issue by nyarly** [lo48576/iri-string#40]
I have an application where I'd like to track the variables visited while expanding a URITemplateStr; currently that requires a pair of `Arc<Mutex<_>>` to avoid the mutability constraint on `Context` - it'd be great if the `Context` trait's `visit()` received `&mut self`.

Since that would likely be a breaking change, could we add a `MutContext`/`visit_mut()` and a corresponding method on `UriTemplateStr` (i.e. `expand_mut()`)?

**Comment by lo48576** [comment]
I don't think it's desirable to make `Context` mutable during the expansion, because it can make `<template::Expanded as std::fmt::Display>::fmt` harder to implement (`Display::fmt receives `&self`). However, it sounds like valid use case to track the used/unused variables.

I'll think how it can be done.

**Comment by lo48576** [comment]
@nyarly, could you explain a bit more about the expected use case?

It would be relatively easy to know whether a variable is visited, but it would be hard to get how many times a variable is visited, because the variables can be visited during the typecheck process. (Note that some [modifiers](https://www.rfc-editor.org/rfc/rfc6570.html#section-2.4) can only be used for limited types of variables.)
And, if the list of "variables" (but not its subcomponents such as specific entry in a dictionary) is needed, it would be more performant and simple to do it during the validation and parsing of `UriTemplateStr`, not during the expansion.

**Comment by nyarly** [comment]
I definitely want to know the list of variables for which the `Context` calls `visit_undefined`. I would probably like to know the list of variables the `Context` provide, but which the `Visitor` didn't visit.

The goal here is to have a kind of limited typechecking on URITemplates - certainly there are cases for leaving variables undefined, or "over-providing" (e.g. a global dictionary provided for several expansions), so I don't want to be completely proscriptive, but catching errors between variables provided and variables expected would be welcome.

**Comment by lo48576** [comment]
Hi @nyarly, could you look into (or try using) #41?

You can generate the doc by `cargo doc` or `cargo +nightly rustdoc --all-features -- --cfg docsrs` and read the documentation of `template::context::DynamicContext` trait. It contains simple example usage of the expansion with dynamic context and visits tracking.

**Comment by lo48576** [comment]
If it looks good to you, I'll merge it and release it as v0.7.4.

**Comment by lo48576** [comment]
Released as [v0.7.4](https://crates.io/crates/iri-string/0.7.4).
