### ISSUE TITLE
RiRelativeStr doesn't have fragment_str method

### ISSUE THREAD

**Issue by silverpill** [lo48576/iri-string#44]
`RiRelativeStr` type has `fragment` method but not `fragment_str` (other methods like `query` have their `_str` counterparts).
Is there a particular reason for that?

**Comment by lo48576** [comment]
Good catch! It's just because of the historical reason... the fragment string type is old and the query string type is new.

The fragment string type is added at 1c5e06192cf88a76f087b01a91bad2ce8039f212, and at the same time `fragment()` is added. The fragment string type can be easily (and sometimes semi-automatically) convertible to `str`, so at that time I don't think `fragment_str()` is necessary.

In contrast, the query string type is added much later than the component getters, so I should have had to use generi c `str` types for getters (such as `query_str()`). And until now, it remains in the API even after `query()` is added. I didn't remove them because some users may have already been using it and the removal is unnecessary.

Anyway, it's true that the API looks a bit inconsistent. I'm not sure it's worth adding `fragment_str() -> Option<&str>`, which is essentially `self.fragment().map(AsRef::as_ref)`, but I'll add if users want.

**Comment by silverpill** [comment]
`fragment().map()` is what I ended up using, but I think it would be nice to have `fragment_str()` in addition to other `*_str()` methods which are really handy

**Comment by lo48576** [comment]
Implemented at b0e9be572d1f and released as v0.7.6.

**Comment by silverpill** [comment]
Thank you!
